### ISSUE TITLE
WriteErrorException: One or more ...

### ISSUE THREAD

**Issue by perp1exed** [ggarbuglia/TfsExtensions#1]
Hi,

Thanks for the upload.

On deployment, after successfully creating credentials, the task fails with the following message:

`##[error]Microsoft.PowerShell.Commands.WriteErrorException: One or more computer names are not valid. If you are trying to pass a URI, use the -ConnectionUri parameter, or pass URI objects instead of strings.`

The credentials I set are valid so not sure what the issue is.

thanks.

**Comment by ggarbuglia** [comment]
Hi perp1exed. Sorry for the delay.

As you may see I have many TFS/TS extensions. Which one are you having trouble with?
By the way I think the problem is not the credentials, but the server name. Try both, the BIOS name [server] or the FQDN [server.full.domain]

Thank you for helping me to improve my extensions!
