### ISSUE TITLE
Having AssemblyVersion("1.0.*") will break the build

### ISSUE THREAD

**Issue by molszews** [ggarbuglia/TfsExtensions#2]
If you create a new project from a template then AssemblyInfo.cs file will have the following line inside:
`// [assembly: AssemblyVersion("1.0.*")]`
This would cause an error during build because of the following reason:
`Microsoft.PowerShell.Commands.WriteErrorException: Cannot convert value "1.0.*" to type "System.Version". Error: "Input string was not in a correct format."`
For now the solution is to manually find&remove these lines.

**Comment by ggarbuglia** [comment]
molszews you are right! If you see the error message "1.0.*" can not be converted to type "System.Version". Thats because System.Version type is composed by Mayor, Minor, Build and Revision numbers. Also in the [Readme.md](https://marketplace.visualstudio.com/items?itemName=ggarbuglia.setassemblyversion-task) I was very specific about the pattern to use for replacemente. You must change manually all Assembly numbers with find & replace in order to let the extensión make the propper work. Thank you again!

**Comment by molszews** [comment]
So it is not a bug, it is a feature that extension is breaking a build? I think it should ignore all not-well formed AssemblyVersions attribute. Fix could be as easy as replacing existing regexp with something like: `
\[assembly: AssemblyVersion\("(\d+\.\d+\.\d+\.\d+)"\)\]` so you are processing only correct entries. Other solution is to skip lines that starts with `\\`

**Comment by ggarbuglia** [comment]
Or... maybe I can add a dropdown field so you guys can specify the pattern you like 1.0, 1.0.0 or System.Version... Cool! I'll keep you posted!

**Comment by willapp** [comment]
Why was this closed without the pull request being merged? The fix supplied by @molszews would be really useful, without it this task isn't useful unless you remember to remove the default comment!!
